which bundle

diff --git a/create-rails-app b/create-rails-app
--- a/create-rails-app
+++ b/create-rails-app
@@ -17,15 +17,14 @@ main() {
   #
   cd $DIR
   git clone -b $TARGET --single-branch https://github.com/rails/rails
+  which bundle
 }
 
 prereq_ruby_version() {
   expected_version=$(curl -s https://cache.ruby-lang.org/pub/ruby/index.txt | tail -n 1 | cut -f1 | cut -d '-' -f2)
   found_version=$(ruby -v | perl -nle 'm/ruby ([\d\.]*)/; print $1')
-  if [ "$expected_version" = "$found_version" ]; then
-    echo "Ruby version $found_version detected"
-  else
-    echo "Ruby version $expected_version expected"
+  if ! [ "$expected_version" = "$found_version" ]; then
+    echo "error: Ruby $expected_version expected"
     exit 1
   fi  
 }
